-- 1. Create Recipes Table
CREATE TABLE recipes (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  origin TEXT,
  continent TEXT,
  description TEXT,
  prep_time TEXT,
  cook_time TEXT,
  difficulty TEXT,
  ingredients JSONB,
  method JSONB,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Create Favorites Table
CREATE TABLE favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_id TEXT REFERENCES recipes(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  UNIQUE(user_id, recipe_id)
);

-- 3. Create Shopping List Table
CREATE TABLE shopping_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item TEXT NOT NULL,
  is_checked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopping_list ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- Recipes: Everyone can read
CREATE POLICY "Public Recipes Access" ON recipes FOR SELECT USING (true);

-- Favorites: Users can only see/manage their own
CREATE POLICY "Users Manage Own Favorites" ON favorites
  FOR ALL USING (auth.uid() = user_id);

-- Shopping List: Users can only see/manage their own
CREATE POLICY "Users Manage Own Shopping List" ON shopping_list
  FOR ALL USING (auth.uid() = user_id);
